In [5]:
import numpy as np
import matplotlib.pyplot as plt
import copy
import random

slots = 4
disc = 12
std = 12

distr = np.array([[1,2,3,4,5],
                 [6,7,8,9],
                 [10,11,12],
                 [1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [1,2,3,5],
                 [6,7,8],
                 [4,9,10,11,12],
                 [1,2,4,5],
                 [3,6,7,8],
                 [9,10,11,12]],dtype=object)

def enroled (std,disc):
    check_disc = distr[disc]
    if std in check_disc: return True
    else: return False
    
def imcomp(d1,d2):
    count = 0
    for student in range (1,std+1):
        if enroled(student,d1) and enroled(student,d2): count+=1
    return count

def evaluate(solu):
    evals = 0
    for d1 in range(0,disc-1):
        for d2 in range (d1+1,disc):
            if solu[d1] == solu[d2]:
                evals += 1

    return evals

In [6]:
#Tests
print('   1  2  3  4  5  6  7  8  9 10 11 12')
for d1 in range(0,disc):
        print(d1+1, end='  ')
        for d2 in range (0,disc):
            print(imcomp(d1,d2), end='  ')
        print()

   1  2  3  4  5  6  7  8  9 10 11 12
1  5  0  0  4  1  0  4  0  1  4  1  0  
2  0  4  0  0  3  1  0  3  1  0  3  1  
3  0  0  3  0  0  3  0  0  3  0  0  3  
4  4  0  0  4  0  0  3  0  1  3  1  0  
5  1  3  0  0  4  0  1  3  0  1  3  0  
6  0  1  3  0  0  4  0  0  4  0  0  4  
7  4  0  0  3  1  0  4  0  0  3  1  0  
8  0  3  0  0  3  0  0  3  0  0  3  0  
9  1  1  3  1  0  4  0  0  5  1  0  4  
10  4  0  0  3  1  0  3  0  1  4  0  0  
11  1  3  0  1  3  0  1  3  0  0  4  0  
12  0  1  3  0  0  4  0  0  4  0  0  4  


In [4]:
# Increment a random's discipline slot
def neighbor1 (solu):
    neig = copy.deepcopy(solu)
    randomIdx = int(random.random() * (len(solu) - 1))
    neig[randomIdx] = (neig[randomIdx] + 1) % slots
    return neig

# switch 2 random discipline's slots
def neighbor2(solu):
    neig = copy.deepcopy(solu)
    randomIdx1 = int(random.random() * (len(solu) - 1))
    while 1:
        randomIdx2 = int(random.random() * (len(solu) - 1))
        if randomIdx2 != randomIdx1:
            break
    aux = neig[randomIdx1]
    neig[randomIdx1] = neig[randomIdx2]
    neig[randomIdx2] = aux
    
    return neig
            
def neighbor3 (solu):
    if np.random.randint(0,2)==0:
        return neighbor1(solu)
    else:
        return neighbor2(solu)

In [10]:
#Tests
sol=np.random.randint(1,slots+1,disc)
print(sol)
for d in range(1,11):
    print(sol, neighbor1(sol))
print(sol)
for d in range(1,11):
    print(sol, neighbor2(sol))

[2 1 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 3 2 3 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 3 2 2 1 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 2 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 3 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 3 3 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 3 2 2 2 2 2 1 3]
[2 1 4 1 3 2 2 2 2 2 1 2] [1 1 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [4 1 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [4 1 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 3 2 2 1 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 2 4 1 3 2 2 1 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 3 2 2 2 2 1 2 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [1 2 4 1 3 2 2 2 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 2 4 1 3 2 2 1 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 2 4 1 3 2 2 2 2 1 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 2 1 3 2 2 4 2 2 1 2]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 2 4 1 3 2 2 2 2 2 1 1]
[2 1 4 1 3 2 2 2 2 2 1 2] [2 1 4 1 2 2 2 3 2 2 1 2]
[2 1 4 1 3 2

In [5]:
def hillclimbing():
    it = 0 ; itNoImp = 0
    #sol = ...
    #sol_eval = ...
    print('initial eval',evaluate(sol))
    while itNoImp < 10000:
        it += 1; itNoImp += 1
        #...
        #print(it, ') ',sol, ' -> ', neig, ':', neig_eval )
        if (neig_eval < sol_eval): 
            #...
            print(it, ') Solution - ',sol, ":", sol_eval )
    return sol

In [6]:
def simulatedAnnealing():
    it = 0 ; itNoImp = 0
    T = 1000
    #...
    while itNoImp < 10000:
        T = T_schedule(T)
        #...
    return solF
    

In [7]:
def T_schedule(T):
    T = 0.999*T
    return T

In [8]:
def initial_solution():
    sol=np.random.randint(1,slots+1,disc)
    #sol=[1,1,1,1,1,1,1,1,1,1,1,1]
    #sol=[1,1,1,2,2,2,3,3,3,4,4,1]
    #sol=[1,1,4,2,2,2,3,3,3,4,4,1]
    #sol=[1,2,3,4,1,2,3,4,1,2,3,4]
    #sol=[3,3,3,4,4,2,1,1,1,2,2,4]
    return sol
    

In [10]:
hc = hillclimbing()
print(hc, ':', evaluate(hc))

initial eval 10
6 ) Solution -  [1 4 1 2 1 2 2 3 3 4 2 4] : 7
17 ) Solution -  [1 4 1 4 1 2 2 3 3 4 2 4] : 6
19 ) Solution -  [1 4 1 4 1 2 2 3 3 3 2 4] : 4
[1 4 1 4 1 2 2 3 3 3 2 4] : 4


In [13]:
sa = simulatedAnnealing()
print(sa, ':', evaluate(sa))

4 ) Solution -  [3 1 2 1 3 2 2 2 1 4 1 4] : 10
46 ) Solution -  [4 4 3 3 2 2 2 1 1 2 3 4] : 7
152 ) Solution -  [2 1 1 4 4 4 3 2 3 1 3 4] : 5
162 ) Solution -  [1 1 1 4 3 4 2 2 3 2 4 2] : 4
565 ) Solution -  [3 2 4 1 4 3 2 1 2 4 3 1] : 3
2692 ) Solution -  [3 3 4 1 1 2 2 2 3 4 4 1] : 2
6856 ) Solution -  [1 4 4 2 2 1 4 1 3 3 3 2] : 1
7046 ) Solution -  [3 3 3 4 4 2 1 1 1 2 2 4] : 0
[3 3 3 4 4 2 1 1 1 2 2 4] : 0
